name: staggered_grid_view
version: 0.0.1
description: A flexible and performant Flutter package for creating staggered grid layouts.
repository: https://github.com/AKB0N/staggered_grid_view

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: '>=3.27.0'

